# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.38262165 0.89048052 0.60208943]
  [0.70454236 0.59935705 0.77388425]
  [0.23984924 0.85924349 0.09308061]]

 [[0.33459816 0.25402017 0.16753398]
  [0.03321131 0.14131497 0.61315423]
  [0.41590591 0.73140011 0.70418037]]

 [[0.71962122 0.04412282 0.10288877]
  [0.91053099 0.12464218 0.88907497]
  [0.80906216 0.60357741 0.92797578]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [1]:
diag = np.diag(1+np.arange(4), k = -1)
print (diag)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
array= np.array([[0,1], [1,0]])
cb = np.tile(array,(4,4))
print (cb)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
rm = np.random.random((5,5))
rm_max, rm_min = rm.max(), rm.min()
rm= (rm-rm_min)/(rm_max-rm_min)
print (rm)

<IPython.core.display.Javascript object>

[[0.64766614 0.22251379 0.35160345 0.13636721 0.48351357]
 [0.73165554 0.54242446 0.04214815 0.29676162 0.67497097]
 [0.44583335 0.23545981 0.45751076 0.17392079 0.13073297]
 [0.4163674  0.34416193 0.11655229 0.9195984  0.47370443]
 [0.27218302 0.63120649 1.         0.62849133 0.        ]]


# 5.  How to find common values between two arrays?

In [8]:
array1 = np.random.randint(10, size=10)
print("Array1: ",array1)
array2 = np.random.randint(20, size=10)
print("Array2: ",array2)
print("\nCommon values between two arrays:")
print(np.intersect1d(array1, array2))

<IPython.core.display.Javascript object>

Array1:  [3 3 4 0 3 6 4 6 3 9]


<IPython.core.display.Javascript object>

Array2:  [15  1  9 10 15 17  1 17 15  2]

Common values between two arrays:


<IPython.core.display.Javascript object>

[9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
yest = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yest)
tod     = np.datetime64('today', 'D')
print("Today: ",tod)
tom  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tom)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Yestraday:  2020-07-25


<IPython.core.display.Javascript object>

Today:  2020-07-26


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [11]:
array1 = np.random.randint(5, size=5)
print("Array1: ",array1)
array2 = np.random.randint(6, size=5)
print("Array2: ",array2)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(array1, array2)
print(array_equal)

<IPython.core.display.Javascript object>

Array1:  [4 3 1 0 4]


<IPython.core.display.Javascript object>

Array2:  [4 3 3 3 4]
Test above two arrays are equal or not!


<IPython.core.display.Javascript object>

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
array1 = np.random.randint(20, size=10)
print(array1)
array1[array1.argmax()] = 0
print(array1)

<IPython.core.display.Javascript object>

[15 14 16 10 17 19 19 16 18  9]
[15 14 16 10 17  0 19 16 18  9]


# 9. How to print all the values of an array?

In [27]:
my_array = np.random.randint(2, size=9999)
np. set_printoptions(threshold=np. inf)
print(my_array)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 0 1 0 0 0
 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 1
 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 0
 1 1 1 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 1
 1 1 0 1 1 1 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1
 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 0 1 1 1 0
 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1
 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0
 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1
 0 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 1 1 1 1 1 0
 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1
 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 0
 1 1 0 0 0 1 0 0 0 1 0 1 

# 10.Subtract the mean of each row of a matrix

In [36]:
X = np.random.rand(5,5)
print(X)
Y = X - X.mean(axis=1, keepdims=True)

print("\n",Y)

<IPython.core.display.Javascript object>

[[0.01207224 0.90538968 0.49786992 0.86989681 0.06230767]
 [0.90480761 0.36041182 0.55755197 0.86666328 0.10010166]
 [0.57939292 0.73105152 0.88778025 0.04396813 0.83681216]
 [0.50083196 0.24407349 0.31696982 0.98873267 0.44265359]
 [0.61295526 0.49348773 0.80043707 0.66588321 0.39271888]]

 [[-4.57435028e-01  4.35882417e-01  2.83626566e-02  4.00389544e-01
  -4.07199590e-01]
 [ 3.46900347e-01 -1.97495450e-01 -3.55299744e-04  3.08756010e-01
  -4.57805607e-01]
 [-3.64080702e-02  1.15250527e-01  2.71979251e-01 -5.71832869e-01
   2.21011161e-01]
 [ 2.17965629e-03 -2.54578814e-01 -1.81682487e-01  4.90080361e-01
  -5.59987154e-02]
 [ 1.98588334e-02 -9.96087050e-02  2.07340640e-01  7.27867777e-02
  -2.00377546e-01]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [41]:
arr1= np.random.randint(0,5,10)
print(arr1)
arr2= np.random.randint(0,8,10)
print (arr2)

<IPython.core.display.Javascript object>

[1 4 3 3 3 0 1 4 0 3]


<IPython.core.display.Javascript object>

[3 3 0 2 3 2 4 2 2 7]


In [42]:
arr1 += np.bincount(arr2, minlength=len(arr1))

print (arr1)

<IPython.core.display.Javascript object>

[2 4 7 6 4 0 1 5 0 3]


# 12.How to get the diagonal of a dot product?

In [45]:
x = np.random.randint(0,10,(3,3))
print(x)
y = np.random.randint(0,10,(3,3))
print(y)
print("Diagonal of a dot product")
print (np.diag(np.dot(x,y)))

<IPython.core.display.Javascript object>

[[5 5 8]
 [5 5 0]
 [4 9 1]]


<IPython.core.display.Javascript object>

[[5 9 9]
 [8 7 8]
 [5 6 8]]
Diagonal of a dot product


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[105  80 116]


# 13.How to find the most frequent value in an array?

In [46]:
x = np.random.randint(0,10,50)
print (x)
print('most frequent:', np.bincount(x).argmax())

<IPython.core.display.Javascript object>

[7 2 9 9 6 8 6 3 1 1 2 3 1 5 1 2 1 5 4 2 6 4 4 9 5 9 4 4 9 9 6 0 6 5 8 7 4
 4 4 8 0 3 8 6 5 6 1 2 5 8]


<IPython.core.display.Javascript object>

most frequent: 4


# 14.How to get the n largest values of an array

In [48]:
x = np.arange(100)
np.random.shuffle(x)
n = 5
print (n," Largest values are : \n")
print (x[np.argsort(x)[-n:]])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

5  Largest values are : 



<IPython.core.display.Javascript object>

[95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [50]:
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
ra = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

print (ra)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
